### Logical Operator

#### AND: $and

<pre>
    db.empDetails.find({
                            $and: 
                            [
                                {e_mail: "melw1@g.com"},
                                {phone:"8197087451"}
                            ]
                       }).pretty()
</pre>
Remember if the multiple condition are then by default <b>and</b> is considered

#### OR: $or

<pre>
    db.empDetails.find({
                            $or: 
                            [
                                {e_mail: "melw3@g.com"},
                                {e_mail: "melw2@g.com"}
                            ]
                       }).pretty()
</pre>

#### eq:  $eq

<pre>
    db.salary.find(
                    { "DEPT": {$eq:"IT"} }
                  )
</pre>

#### Not Equal: $ne


<pre>
       db.salary.find(
                      { "DEPT": { $ne:  "IT" } }
                  ) 
</pre>

##### Alternative way  not equal <pre> $not { $eq: } </pre> 

<pre>
    db.salary.find(
                      { 
                          "DEPT": {
                                      $not: { $eq: "IT" }
                                  } 
                       }
                  )
</pre>


#### Less than: $lt

<pre>
    db.sal.find({"SALARY" :{$lt : 50000}});
</pre>

#### Lesser Than equal to : $lte

<pre>
    db.sal.find({"SALARY" :{$lte : 50000}})
</pre>


#### Greater than: $gt

<pre>
    db.sal.find({"SALARY" :{$gt : 50000}});
</pre>

#### Greater than equal to: $gte

<pre>
    db.sal.find({"SALARY" :{$gte : 50000}});
</pre>

#### 


#### nor (combination of NOT and OR)

<pre>
    db.salary.find(
                    {
                        $nor: [
                                {"DESI":"ASSOCIATE"},
                                {"DEPT":"HR"}
                        ]
                    }
    )
</pre>
In the above code 
you will be getting all those records not having "DESI" == "ASSOCIATE" and "DEPT" == "HR"

### IN : $in

represents values in an array same as where dept in (‘hr’, ‘it’, ’admin’) <br>

    
<pre>
    db.sal.find({
                    "DEPT" :{
                                $in : ["HR", "IT", "TEMP"]
                            }
                }); 
</pre>

### NOTIN: $nin

represents values not in an array

<pre>
       db.sal.find({
                    "DEPT" :{
                                $nin : ["HR", "IT", "TEMP"]
                            }
                });  
</pre>

### To get the Count of the record
<pre>
    db.sal.find().count()
</pre>

### Limiting Documents

<pre>
    db.salary.find({}).limit(10);
</pre>

### Sorting Documents
<p>method is used to sort the documents. <br>
   The method accepts a document containing a list of fields along with their sorting order.<br> 
    1 is used for ascending order while -1 is used for descending order.
</p>
<pre>
    Syntax
    db.COLLECTION_NAME.find().sort({KEY:1})
    
    ex
    
    db.salary.find({}).limit(5).sort({"SALARY" : 1});
    db.salary.find({},{"EID" : 1 , "DESI" : 1}).limit(5).sort({"EID" : 1})
</pre>

## Indexing
<p>
Indexing is done for the faster retrial of data. Without indexes,<br>
MongoDB must scan every document of a collection to select those<br>
documents that match the query statement
</p>

### Type of Index

<ul>
<li><b>Default_id</b> – every collection contains an index on default _id field.</li>
<li><b>Single Field</b> – An index created on a single field in ascending or
descending order.</li>
<li><b>Compound Index</b> – An index based on multiple fields (max 31)</li>
<li><b>Multi-Key Index</b> – index created on array field</li>
<li><b>TTL Index</b> – TTL (Total Time to Live) are created for a limited time</li>
<li><b>Unique Index</b> – ensures the uniqueness of the field</li>
</ul>

#### Create index

<pre>
Syntax
    db.collectionname.createIndex()
</pre>

#### Single Field

<pre>
     db.emp3.createIndex({"City" : 1}) ;
</pre>

#### Compound Index

<pre>
    db.emp3.createIndex({"EID" : 1, "City" : 1}); 
</pre>

#### TTL Index – TTL (Total Time to Live) are created by combining “expireAfterSeconds” and createIndex().

<pre>
    db.emp3.createIndex({"EID" : 1},{expireAfterSeconds:600});
</pre>

<b>TTL Limitations:</b>
<ul>
<li>Compound Indexes can not be created as TTL</li>
<li>Can not be created on capped collections</li>
<li>Cannot be created on the field on which other index exists</li>
</ul>

#### Unique Index – 
<p>to create a unique index we need to set the unique
option of createIndex() method to true</p>

<pre>
    Syntax
    db.collectionname.createIndex({key: 1},{unique:true})
    
    ex
    db.emp3.createIndex({"EID" : 1},{unique:true});
</pre>

#### Find index – 
<pre>
Syntax
    db.collectionname.getIndexes()
</pre>

#### Drop index – 
<pre>
Syntax
    db.collectionname.dropIndex()
</pre>

#### Drop All index - 
<pre>
Syntax
    db.collectionname.dropIndexes();
</pre>